name: quiz_application
description: "A Quiz Application with Dynamic Questions."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: BalooBhai2
      fonts:
        - asset: fonts/BalooBhai2-VariableFont_wght.ttf